"""Workspace directory management, cleanup, purge scheduler, and binary lifecycle."""

from __future__ import annotations

import atexit
import io
import os
import platform
import shutil
import signal
import threading
import urllib.request
import zipfile
from datetime import UTC, datetime
from pathlib import Path

from loguru import logger

from src.core.config import AppConfig
from src.core.constants import (
    GRADIO_TEMP_DIR,
    USER_AGENT,
    WORKSPACE_ROOT,
    WORKSPACE_TMP,
)

# Guard flag: skip purge during active downloads
ACTIVE_DOWNLOAD_EVENT = threading.Event()

# Media file extensions generated by YT-DL (used by tmp/ recursive purge)
_MEDIA_EXTENSIONS: frozenset[str] = frozenset({".mp3", ".mp4", ".aac", ".opus"})


def init_workspace(config: AppConfig) -> None:
    """Create all workspace subdirectories if they don't exist.

    Args:
        config: Application config with workspace paths.
    """
    logger.info("Setting up workspace directories...")
    dirs = [
        config.workspace.bin,
        config.workspace.audios,
        config.workspace.videos,
        config.workspace.tmp,
        config.workspace.logs,
        GRADIO_TEMP_DIR,
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


def clean_dir(directory: Path) -> None:
    """Delete all contents of a directory without removing the directory itself.

    Args:
        directory: Directory to clean.
    """
    if not directory.exists():
        return

    # Count before cleaning for summary
    files = [f for f in directory.rglob("*") if f.is_file()]
    count = len(files)
    size_mb = sum(f.stat().st_size for f in files) / (1024 * 1024)

    for item in directory.iterdir():
        if item.is_dir():
            shutil.rmtree(item, ignore_errors=True)
        else:
            item.unlink(missing_ok=True)

    if count > 0:
        logger.info(
            "Workspace Cleaner - Purged {} files, freeing {:.2f} MB.",
            count,
            size_mb,
        )


def cleanup_tmp() -> None:
    """Delete contents of workspace/tmp without removing the directory itself.

    Preserves the directory inode so any existing path references stay valid.
    At startup cleans staging leftovers; the hardlink serve dir is also removed.
    Gradio recreates tmp/gradio/ on demand — no need to pre-create it.
    """
    clean_dir(WORKSPACE_TMP)
    WORKSPACE_TMP.mkdir(parents=True, exist_ok=True)


def run_purge_cycle(config: AppConfig) -> None:
    """Scan workspace directories and delete expired content.

    Target table maps directory → retention_days → recursive flag.
    Skips if active download in progress.
    Skips dirs with retention_days == -1 (never purge).

    Args:
        config: Application config with retention settings.
    """
    if ACTIVE_DOWNLOAD_EVENT.is_set():
        return

    logger.info("Workspace Cleaner - Starting scheduled cache purge cycle...")

    # Target table: (path, retention_days, recursive)
    targets: list[tuple[Path, int, bool]] = [
        (config.workspace.audios, config.cleaner.retention.audio_days, False),
        (config.workspace.videos, config.cleaner.retention.video_days, False),
        (GRADIO_TEMP_DIR, config.cleaner.retention.tmp_days, True),
        (WORKSPACE_TMP / "serve", config.cleaner.retention.tmp_days, True),
    ]

    total_files = 0
    total_mb = 0.0

    for directory, retention_days, recursive in targets:
        if retention_days == -1:
            continue
        files, mb = _purge_dir(directory, retention_days, recursive)
        total_files += files
        total_mb += mb

    if total_files > 0:
        logger.info(
            "Workspace Cleaner - Purged {} files, freeing {:.2f} MB.",
            total_files,
            total_mb,
        )
    else:
        logger.info("Workspace Cleaner - Purge cycle completed. No stale files found.")


def _purge_dir(
    directory: Path,
    retention_days: int,
    recursive: bool = False,
) -> tuple[int, float]:
    """Purge expired files from a directory.

    Args:
        directory: Directory to scan.
        retention_days: Retention policy (-1=skip, 0=immediate, N=days).
        recursive: If True, purge individual files. If False, purge whole subdirs.

    Returns:
        Tuple of (files_deleted, megabytes_freed).
    """
    if retention_days == -1:
        return 0, 0.0

    if not directory.exists():
        return 0, 0.0

    files_deleted = 0
    mb_freed = 0.0
    now = datetime.now(UTC)

    if recursive:
        # Purge media files in tmp/ (preserve Gradio assets)
        for path in directory.iterdir():
            if path.is_file() and path.suffix.lower() in _MEDIA_EXTENSIONS:
                if retention_days == 0:
                    size = path.stat().st_size
                    path.unlink(missing_ok=True)
                    files_deleted += 1
                    mb_freed += size / (1024 * 1024)
                else:
                    age_days = (now.timestamp() - path.stat().st_mtime) / 86400
                    if age_days > retention_days:
                        size = path.stat().st_size
                        path.unlink(missing_ok=True)
                        files_deleted += 1
                        mb_freed += size / (1024 * 1024)

        # Remove empty subdirectories after file purge
        for path in directory.iterdir():
            if path.is_dir() and not any(path.iterdir()):
                path.rmdir()
    else:
        # Purge whole VIDEO_ID subdirs in audios/videos
        for video_dir in directory.iterdir():
            if not video_dir.is_dir():
                continue

            if retention_days == 0:
                count, mb = _dir_size(video_dir)
                shutil.rmtree(video_dir)
                files_deleted += count
                mb_freed += mb
                continue

            try:
                oldest = _oldest_mtime(video_dir)
            except (ValueError, OSError):
                continue

            age_days = (now.timestamp() - oldest) / 86400
            if age_days > retention_days:
                count, mb = _dir_size(video_dir)
                shutil.rmtree(video_dir)
                files_deleted += count
                mb_freed += mb

    return files_deleted, mb_freed


def _dir_size(directory: Path) -> tuple[int, float]:
    """Count files and total size of a directory tree.

    Args:
        directory: Directory to measure.

    Returns:
        Tuple of (file_count, size_in_mb).
    """
    count = 0
    total_bytes = 0
    for f in directory.rglob("*"):
        if f.is_file():
            count += 1
            total_bytes += f.stat().st_size
    return count, total_bytes / (1024 * 1024)


def _oldest_mtime(directory: Path) -> float:
    """Find the oldest file modification time in a directory tree.

    Args:
        directory: Directory to scan.

    Returns:
        Oldest mtime as Unix timestamp.

    Raises:
        ValueError: If directory is empty.
    """
    oldest = float("inf")
    for f in directory.rglob("*"):
        if f.is_file():
            mtime = f.stat().st_mtime
            if mtime < oldest:
                oldest = mtime

    if oldest == float("inf"):
        raise ValueError(f"Directory is empty: {directory}")

    return oldest


def get_disk_usage(path: Path) -> dict[str, int]:
    """Calculate disk usage per subdirectory.

    Args:
        path: Directory to scan.

    Returns:
        Dict mapping directory name to total size in bytes.
    """
    usage: dict[str, int] = {}

    if not path.exists():
        return usage

    for entry in path.iterdir():
        if entry.is_dir():
            total = sum(f.stat().st_size for f in entry.rglob("*") if f.is_file())
            usage[entry.name] = total

    return usage


_CACHE_DIRS: dict[str, Path] = {
    "audios": WORKSPACE_ROOT / "audios",
    "videos": WORKSPACE_ROOT / "videos",
    "tmp": WORKSPACE_TMP,
    "logs": WORKSPACE_ROOT / "logs",
}


def cache_usage() -> list[dict[str, object]]:
    """Per-directory disk usage for the workspace cache.

    Returns:
        List of dicts with name, size_mb, count, oldest_days per directory.
    """
    now = datetime.now(UTC).timestamp()
    rows: list[dict[str, object]] = []

    for name, path in _CACHE_DIRS.items():
        stats = (
            [p.stat() for p in path.rglob("*") if p.is_file()] if path.exists() else []
        )
        size_mb = sum(s.st_size for s in stats) / (1024 * 1024)
        oldest_days = (now - min(s.st_mtime for s in stats)) / 86400 if stats else None
        rows.append(
            {
                "name": name,
                "size_mb": round(size_mb, 2),
                "count": len(stats),
                "oldest_days": oldest_days,
            }
        )

    return rows


def register_cleanup_hooks() -> None:
    """Register atexit and signal handlers to clean workspace/tmp on shutdown."""

    def _cleanup() -> None:
        """Run tmp directory cleanup."""
        cleanup_tmp()

    atexit.register(_cleanup)

    def _signal_handler(_signum: int, _frame: object) -> None:
        """Handle SIGINT/SIGTERM by cleaning up then exiting."""
        _cleanup()
        raise SystemExit(0)

    signal.signal(signal.SIGINT, _signal_handler)
    signal.signal(signal.SIGTERM, _signal_handler)


def start_purge_scheduler(config: AppConfig) -> threading.Thread | None:
    """Start background purge thread.

    Returns None if scheduler is disabled in config.

    Args:
        config: Application config.

    Returns:
        Daemon thread, or None if disabled.
    """
    import time

    if not config.cleaner.scheduler.enabled:
        logger.info("Workspace Cleaner - Scheduler disabled in config, skipping")
        return None

    interval = config.cleaner.scheduler.interval_hours

    def _loop() -> None:
        """Run purge cycle at configured interval."""
        while True:
            time.sleep(interval * 3600)
            run_purge_cycle(config)

    thread = threading.Thread(target=_loop, daemon=True)
    thread.start()
    logger.info(
        "Workspace Cleaner - Scheduler started, runs every {} hour(s)", interval
    )
    return thread


def check_binary(name: str, bin_dir: Path) -> bool:
    """Check if a binary exists in bin_dir.

    Args:
        name: Binary name (e.g. "ffmpeg", "bun").
        bin_dir: Directory to check.

    Returns:
        True if binary exists and is a file.
    """
    exe = name + (".exe" if os.name == "nt" else "")
    path = bin_dir / exe
    return path.is_file()


def ensure_ffmpeg(bin_dir: Path) -> Path:
    """Ensure ffmpeg (and ffprobe) are available.

    Tries static_ffmpeg download first. Falls back to system ffmpeg
    from PATH — no symlinks, no copies.

    Args:
        bin_dir: Target directory for static_ffmpeg binaries.

    Returns:
        Path to ffmpeg binary (may be outside bin_dir via system fallback).
    """
    ffmpeg_name = "ffmpeg.exe" if os.name == "nt" else "ffmpeg"

    # Clean up stale symlinks from old code (volume migration)
    ffmpeg_path = bin_dir / ffmpeg_name
    if ffmpeg_path.is_symlink():
        ffmpeg_path.unlink()
    ffprobe_path = bin_dir / ("ffprobe.exe" if os.name == "nt" else "ffprobe")
    if ffprobe_path.is_symlink():
        ffprobe_path.unlink()

    if check_binary("ffmpeg", bin_dir):
        return ffmpeg_path

    bin_dir.mkdir(parents=True, exist_ok=True)

    try:
        from static_ffmpeg.run import get_or_fetch_platform_executables_else_raise

        ffmpeg_exe, ffprobe_exe = get_or_fetch_platform_executables_else_raise()
        shutil.copy(ffmpeg_exe, bin_dir)
        shutil.copy(ffprobe_exe, bin_dir)
        logger.info("Downloaded video processing tools...")
        return bin_dir / ffmpeg_name
    except Exception:
        system_ffmpeg = shutil.which("ffmpeg")
        if system_ffmpeg:
            logger.info("Using system ffmpeg at {}", system_ffmpeg)
            return Path(system_ffmpeg)
        logger.warning("FFmpeg not found on system")
        return bin_dir / ffmpeg_name


def get_ffmpeg_path(bin_dir: Path) -> Path | None:
    """Resolve ffmpeg binary path dynamically.

    Prefers real file in workspace/bin (static_ffmpeg download).
    Falls back to system ffmpeg via PATH lookup.

    Args:
        bin_dir: Directory that may contain static_ffmpeg binaries.

    Returns:
        Path to ffmpeg binary, or None if not found.
    """
    name = "ffmpeg.exe" if os.name == "nt" else "ffmpeg"

    candidate = bin_dir / name
    if candidate.is_file():
        return candidate

    system_ffmpeg = shutil.which("ffmpeg")
    if system_ffmpeg:
        return Path(system_ffmpeg)

    return None


def ensure_bun(bin_dir: Path) -> Path:
    """Ensure bun binary exists in bin_dir.

    Downloads platform-appropriate bun from GitHub releases.

    Args:
        bin_dir: Target directory for bun.

    Returns:
        Path to bun binary.

    Logs:
        Error on failure (not fatal).
    """
    exe_name = "bun.exe" if os.name == "nt" else "bun"
    bun_path = bin_dir / exe_name

    if check_binary("bun", bin_dir):
        return bun_path

    bin_dir.mkdir(parents=True, exist_ok=True)
    _download_bun(bun_path, exe_name)
    return bun_path


def _extract_bun_binary(zf: zipfile.ZipFile, exe_name: str, bun_path: Path) -> bool:
    """Extract bun binary from a zip archive.

    Args:
        zf: Opened ZipFile object.
        exe_name: Executable name (bun or bun.exe).
        bun_path: Target path for the extracted binary.

    Returns:
        True if extraction succeeded, False if binary not found in archive.
    """
    for member in zf.namelist():
        if member.endswith(f"/{exe_name}") or member == exe_name:
            with zf.open(member) as src, open(bun_path, "wb") as dst:
                shutil.copyfileobj(src, dst)
            return True
    return False


def _download_bun(bun_path: Path, exe_name: str) -> None:
    """Download bun binary from GitHub releases.

    Downloads zip to memory, extracts directly to bin_dir. No temp files.

    Args:
        bun_path: Target path for bun binary.
        exe_name: Executable name (bun or bun.exe).
    """
    system = platform.system().lower()
    machine = platform.machine().lower()
    arch = "aarch64" if machine in ("arm64", "aarch64") else "x64"

    variant = ""
    if system == "linux":
        import glob as _glob

        if any(_glob.glob("/lib/ld-musl-*.so*")):
            variant = "-musl"

    url = (
        "https://github.com/oven-sh/bun/releases/latest/download/"
        f"bun-{system}-{arch}{variant}.zip"
    )

    logger.info("Downloading JavaScript runtime...")

    try:
        req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
        with urllib.request.urlopen(req, timeout=120) as resp:
            zip_data = resp.read()

        with zipfile.ZipFile(io.BytesIO(zip_data)) as zf:
            if not _extract_bun_binary(zf, exe_name, bun_path):
                logger.error("JavaScript runtime download failed — invalid archive")
                return

        if os.name != "nt":
            bun_path.chmod(0o755)

        logger.info("JavaScript runtime ready")
    except Exception:
        logger.error("Could not download JavaScript runtime")
        if bun_path.exists():
            bun_path.unlink()
